booking:
 property: Booking Profile Dev Update
spring:
  jap:
   hbiernate:
    ddl-auto: update
   show-sql: true
   generate-ddl: true
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQLDialect